esotrades/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', include('pages.urls', namespace='pages')),
    url(r'^search/', include('haystack.urls')),
    url(r'^trades/', include('trades.urls', namespace='trades')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/profile', include('userprofiles.urls')),
    url(r'^accounts/', include('registration.backends.default.urls')),
)

pages/urls.py
from django.conf.urls import patterns, url
from pages import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='home'),

)

trades/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from trades import views

urlpatterns = patterns('',

    url(r'^$', views.IndexView.as_view(paginate_by=10), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^new$', login_required(views.CreateView.as_view()), name="new_trade"),
)

userprofiles/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required as auth
from userprofiles import views

urlpatterns = patterns('',
    url(r'^/edit_profile/$', auth(views.UserProfileEditView.as_view()), name="edit_profile"),
    url(r'^/(?P<slug>\w+)/$', views.UserProfileDetailView.as_view(), name='profile'),
)

pages/models.py
from django.db import models

# Create your models here.

trades/models.py
from django.db import models
from django.contrib.auth.models import User


class Trade(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, editable=False, default=None)
    quantity = models.IntegerField(blank=False, default=0)
    start_price = models.IntegerField(default=1)
    buyout_price = models.IntegerField(blank=False, default=1)
    server = models.ForeignKey('Server', blank=False, null=True)
    category = models.ForeignKey('Category', blank=False, null=True)
    trade_type = models.ForeignKey('TradeType', blank=False, null=True)
    trade_duration = models.ForeignKey('TradeDuration', blank=False, null=True)

    def __unicode__(self):
        return self.title


class Category(models.Model):
    title = models.CharField(max_length=255)

    def __unicode__(self):
        return self.title


class Item(models.Model):
    title = models.CharField(max_length=255)

    def __unicode__(self):
        return self.title

class Server(models.Model):
    title = models.CharField(max_length=255)

    def __unicode__(self):
        return self.title

class TradeType(models.Model):
    title = models.CharField(max_length=255)

    def __unicode__(self):
        return self.title

class TradeDuration(models.Model):
    title = models.CharField(max_length=255)

    def __unicode__(self):
        return self.title

userprofiles/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, unique=True)
    bio = models.TextField(null=True)

    def __unicode__(self):
        return "%s's profile" % self.user

def create_profile(sender, instance, created, **kwargs):
    if created:
        profile, created = UserProfile.objects.get_or_create(user=instance)

# Signal while saving user
from django.db.models.signals import post_save
post_save.connect(create_profile, sender=User)

trades/forms.py
from django import forms
from trades.models import Trade, Category, Server, TradeType, TradeDuration


class TradeForm(forms.ModelForm):
    title = forms.CharField(max_length=255, label='Title:')
    server = forms.ModelChoiceField(
        queryset=Server.objects.all(),
        label='Server:',
    )
    trade_type = forms.ModelChoiceField(
        queryset=TradeType.objects.all(),
        label='Type:',
    )
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        label='Category:',
    )
    trade_duration = forms.ModelChoiceField(
        queryset=TradeDuration.objects.all(),
        label='Duration:',

    )
    quantity = forms.IntegerField(label='Quantity:')
    start_price = forms.IntegerField(label='Start Price:')
    buyout_price = forms.IntegerField(label='Buyout Price:')
    body = forms.Textarea()

    class Meta:
        model = Trade

userprofiles/forms.py
from django import forms
from .models import UserProfile

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ("user",)

pages/views.py
from django.shortcuts import render

def index(request):
    context = ''
    return render(request, 'pages/index.html', context)

trades/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic

from trades.models import Trade
from trades.forms import TradeForm


class IndexView(generic.ListView):
    template_name = 'trades/index.html'
    context_object_name = 'trades_list'

    def get_queryset(self):
        return Trade.objects.order_by('-created')


class DetailView(generic.DetailView):
    model = Trade
    template_name = 'trades/detail.html'


class CreateView(generic.CreateView):
    form_class = TradeForm
    template_name = 'trades/new_trade.html'
    success_url = '/trades'

    def form_valid(self, form):
        if form.is_valid():
            trade = form.save(commit=False)
            trade.owner = self.request.user
            trade.save()
        return super(CreateView, self).form_valid(form)

userprofiles/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views.generic import ListView, DetailView, UpdateView
from django.contrib.auth import get_user_model

from userprofiles.models import UserProfile
from userprofiles.forms import UserProfileForm

class UserProfileDetailView(DetailView):
    model = get_user_model()
    slug_field = "username"
    template_name = "userprofiles/profile.html"

    def get_object(self, queryset=None):
        user = super(UserProfileDetailView, self).get_object(queryset)
        UserProfile.objects.get_or_create(user=user)
        return user

class UserProfileEditView(UpdateView):
    model = UserProfile
    form_class = UserProfileForm
    template_name = "edit_profile.html"

    def get_object(self, queryset=None):
        return UserProfile.objects.get_or_create(user=self.request.user)[0]

    def get_success_url(self):
        return reverse("profile", kwargs={'slug': self.request.user})

pages/templates/pages/index.html
{% extends "base.html" %}

{% load latest_trades %}

{% block content %}
    <h1>{% block title %}Elder Scrolls Online Trades &amp; Auctions{% endblock title %}</h1>

    <form method="get" action="{% url 'haystack_search' %}" class="form-inline" role="form">
        {% csrf_token %}
            <div class="input-group col-lg-6 center">
                <input type="text" class="form-control" name="q">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">Search</button>
                </span>
            </div>
    </form>
{% endblock content %}

{% block subcontent %}
    <div class="well col-md-4">{% latest_trades %}</div>
    <div class="well col-md-4">asd</div>
    <div class="well col-md-4">asd</div>
{% endblock subcontent %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>

    {% load staticfiles %}{% load bootstrap3 %}

    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% bootstrap_css %}
    <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/smoothness/jquery-ui.min.css">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="../../assets/js/html5shiv.js"></script>
      <script src="../../assets/js/respond.min.js"></script>
    <![endif]-->
</head>
<body role="document">

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Bootstrap <3</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li class="active"><a href="{% url "pages:home" %}">Home</a></li>
                <li><a href="#about">About</a></li>
                <li><a href="#contact">Contact</a></li>
                {% if user.is_authenticated %}
                    <li><a href="/accounts/logout">Logout</a></li>
                    <li><a href="{% url 'profile' slug=user.username %}"><b>{{ user.username }}</b></a></li>
                {% else %}
                    <li><a href="/accounts/login">Login</a></li>
                    <li><a href="/accounts/register">Register</a></li>
                {% endif %}
            </ul>
        </div><!--/.nav-collapse -->
    </div>

    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_messages %}

    <div class="container">

        <div class="row">
            <div class="well">
                {% block content %}{% endblock content %}
            </div>
        </div>

        <div class="row">
            {% block subcontent %}{% endblock subcontent %}
        </div>

    </div>



    {% block footer_js %}
        <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
        <script src="//code.jquery.com/ui/1.10.4/jquery-ui.min.js"></script>
        {% bootstrap_javascript %}
    {% endblock footer_js %}

</body>
</html>

templates/search/search.html
{% extends 'base.html' %}

{% block content %}
    <h2>Search</h2>

    <form method="get" action=".">
        <table>
            {{ form.as_table }}
            <tr>
                <td>&nbsp;</td>
                <td>
                    <input type="submit" value="Search">
                </td>
            </tr>
        </table>

        {% if query %}
            <h3>Results</h3>

            {% for result in page.object_list %}
                <p>
                    <a href="{{ result.object.get_absolute_url }}">{{ result.object.title }}</a>
                </p>
            {% empty %}
                <p>No results found.</p>
            {% endfor %}

            {% if page.has_previous or page.has_next %}
                <div>
                    {% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous{% if page.has_previous %}</a>{% endif %}
                    |
                    {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next &raquo;{% if page.has_next %}</a>{% endif %}
                </div>
            {% endif %}
        {% else %}
            {# Show some example queries to run, maybe query syntax, something else? #}
        {% endif %}
    </form>
{% endblock %}

trades/templates/trades/detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{% block title %}{{ trade.title }}{% endblock title %}</h1>

    {{ trade.server }}<br />
    {{ trade.category }}<br />
    {{ trade.type }}<br />
    {{ trade.duration }}<br />
    {{ trade.start_price }}<br />
    {{ trade.buyout_price }}<br />
    {{ trade.body }}<br />
{% endblock content %}

trades/templates/trades/index.html
{% extends "base.html" %}

{% block content %}
    <h1>{% block title %}Trades{% endblock title %}</h1>

    {% if trades_list %}
        <ul>
            {% for trade in trades_list %}
                <li><a href="{% url 'trades:detail' trade.id %}">{{ trade.title }}</a></li>
            {% endfor %}
        </ul>

        {% if is_paginated %}
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="/trades?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="/trades?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
        {% endif %}
    {% else %}
        <p>No trades found!</p>
    {% endif %}
    <br />
    <a href="{% url 'trades:new_trade' %}">New Trade</a>
{% endblock content %}

trades/templates/trades/latest_trades.html
<h2>Latest Trades</h2>
<ul class="latest_trades">
{% for trade in trades %}
    <li><a href="{% url 'trades:detail' trade.id %}">{{ trade }}</a></li>
{% endfor %}
</ul>

<a href="{% url 'trades:index' %}">View all trades</a>

trades/templates/trades/new_trade.html
{% extends "base.html" %}

{% block title %}<h1>New Trade</h1>{% endblock %}

{% block content %}
    {% if error_message %}{{ error_message }}{% endif %}

    <form action="{% url 'trades:new_trade' %}" method="post">

        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.label}}
            {{ field }}
            <br />
        {% endfor %}

    <input type="submit" value="Submit" />
    </form>
{% endblock content %}

userprofiles/templates/edit_profile.html
{% extends "base.html" %}

{% block title %}Edit Profile for {{ user.username }}{% endblock title %}

{% block content %}

<form method="post" action="">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Edit">
</form>

{% endblock %}

userprofiles/templates/userprofiles/profile.html
{% extends "base.html" %}

{% block title %}Profile for {{ object.username }}{% endblock title %}

{% block content %}
    {% if object.userprofile.bio %}
    <div>
    <b>Bio:</b>
    {{ object.userprofile.bio }}
    </div>
    {% endif %}
    {% if object.username == user.username %}
    <p><a href='{% url "edit_profile" %}'>Edit my profile</a></p>
    {% endif %}
{% endblock content %}